# Koyeb автоматически определит Python проект и установит зависимости
# Не нужно указывать buildpack или build команды - они определяются автоматически

[deploy]
# Основной сервис - Telegram Bot
[[deploy.services]]
name = "leha-bot"
type = "web" 
instance_type = "nano"
regions = ["fra"]
port = 8080

# Environment variables (устанавливаются через веб-интерфейс Koyeb)
env = [
  "ENVIRONMENT=production",
  "PYTHONPATH=/app",
  "LOG_LEVEL=INFO"
]

# Автоматическое масштабирование
[deploy.services.scaling]
min = 1
max = 1

# Политика перезапуска при ошибках
[deploy.services.restart_policy]
condition = "on-failure"
delay = "5s"
max_attempts = 3